### PR TITLE
Improve addresses

### PR DESCRIPTION
**Pull request by maidmaid**
Hi !

About addresses :
- `address` xml tag has 3 attributes : `addr`, `addrtype` and `vendor`. 
- `address` xml tag can be multiple for example one mac address and one IP address.

This PR improves this.

### CODE REVIEW

**Comment by maidmaid** [comment]
Hi @willdurand, could you review this?

**Comment by maidmaid** [comment]
Any news?

**Comment by willdurand** [comment]
Oups sorry. Looks like I missed this PR. Sounds good to me! Thank you.

**Comment by maidmaid** [comment]
Cool! Could you release ``v0.4.0`` please?

**Comment by willdurand** [comment]
@maidmaid done! https://github.com/willdurand/nmap/releases/tag/v0.4.0

**Pull request merged**
